"""Add is_important to HomeworkTask and Event

Revision ID: c2b96921f6d1
Revises: 8a7395611ccf
Create Date: 2026-05-18 01:38:55.608895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b96921f6d1'
down_revision = '8a7395611ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_important', sa.Boolean(), nullable=False))

    with op.batch_alter_table('homework_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_important', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework_task', schema=None) as batch_op:
        batch_op.drop_column('is_important')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('is_important')

    # ### end Alembic commands ###
